#pragma config(Motor,  port1,           leftWheel,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armLeftFront,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           armLeftBack,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armRightFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armRightBack,  tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int leftSpeed;
	int rightSpeed;
	int armSpeed;

	while (true)
	{
		//To control the left side using channel 3
		if (vexRT[Ch3] > -35 && vexRT[Ch3] < 35)
		{
			leftSpeed = 0;
		}
		else
		{
			leftSpeed = vexRT[Ch3];
		}


		//To control the right side using channel 2
		if (vexRT[Ch2] > -35 && vexRT[Ch2] < 35)
		{
			rightSpeed = 0;
		}
		else
		{
			rightSpeed = vexRT[Ch2];
		}

		motor[leftWheel] = leftSpeed;
		motor[rightWheel] = -rightSpeed;


		//lift up using Button 5U or 6D
		if (vexRT[Btn5U] == 1 || vexRT[Btn6D] == 1)				//moving arm	 up
		{
			armSpeed = 127;
		}
		else
		{
			armSpeed = 0;
		}

		motor[armLeftFront] = armSpeed;
		motor[armLeftBack] = armSpeed;
		motor[armRightFront] = -armSpeed;
		motor[armRightBack] = -armSpeed;

	}
}
