#pragma config(Motor,  port1,           RightFrontWheel, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightBackWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftFrontWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LeftBackWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           StarGrabber,   tmotorNone, openLoop)
#pragma config(Motor,  port7,           LiftArm,       tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main()
{
	// driver control
	while (true)
	{
		getJoystickSettings(joystick);


		if (vexRT[Y1] != 1)
		{
			motor[LeftFrontWheel] = vexRT[Ch3];
			motor[LeftBackWheel] = -vexRT[Ch3];
		}
		else
		{
			motor[LeftFrontWheel] = 0;
			motor[LeftBackWheel] = 0;
		}

		if (vexRT[Y2] != 1) {
			motor[RightBackWheel] = vexRT[Ch2];
			motor[RightFrontWheel] = -vexRT[Ch2];
		}
		else
		{
			motor[RightFrontWheel] = 0;
			motor[RightBackWheel] = 0;
		}

		if (vexRT[05] == 1)
		{
			motor[LiftArm] = 127;
		}
		else if (vexRT[07] == 1)
		{
			motor[LiftArm] = 0;
		}
		else
		{
			motor[LiftArm] = 0;
		}

		if (vexRT[06] == 1)
		{
			motor[StarGrabber] = -70;
		}
		else if (vexRT[08] == 1)
		{
			motor[StarGrabber] = 70;
		}
		else
		{
			motor[StarGrabber] = 0;
		}
	}

}
