#pragma config(Motor,  port1,           RightFrontWheel, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightBackWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftFrontWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LeftBackWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           StarGrabber,   tmotorNone, openLoop)
#pragma config(Motor,  port7,           LiftArm,       tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//TESTING RC EMULATOR CONTROLS FINISHED!!!!!!!!!!!!!!!



#include "JoystickDriver.c"
task main()
{
	// driver control
	while (true)
	{
		getJoystickSettings(joystick);


		if (joystick.joy1_y1 != 1)
		{
			motor[LeftFrontWheel] = joystick.joy1_y1;
			motor[LeftBackWheel] = joystick.joy1_y1;
		}
		else
		{
			motor[LeftFrontWheel] = 0;
			motor[LeftBackWheel] = 0;
		}

		if (joystick.joy1_y2 != 1) {
			motor[RightBackWheel] = -joystick.joy1_y2;
			motor[RightFrontWheel] = -joystick.joy1_y2;
		}
		else
		{
			motor[RightFrontWheel] = 0;
			motor[RightBackWheel] = 0;
		}

		if (joy1Btn(05) == 1)
		{
			motor[LiftArm] = 127;
		}
		else if (joy1Btn(07) == 1)
		{
			motor[LiftArm] = -127;
		}
		else
		{
			motor[LiftArm] = 0;
		}

		if (joy1Btn(06) == 1)
		{
			motor[StarGrabber] = -100;
		}
		else if (joy1Btn(08) == 1)
		{
			motor[StarGrabber] = 100;
		}
		else
		{
			motor[StarGrabber] = 0;
		}
	}

}
