#pragma config(Motor,  port1,           frontRight,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftUp,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightUp,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task autonomous() {
	//Start
	putUpLift();
	turn('R', 90);
	putDownLift ();
	putUpLift();
	turn('L', 90);

	//Move towards fence
	move('F', 2);

	//Sweep fence
	move('L', 90);
	move('F', 4);

	//2nd Sweep
	turn('R', 180);

	turn('L', 90);
	move('F', 2);

	putUpLift();
	move('F', 2);
	openStarGrabber();
	move('B', 1);
	putDownLift();

	//Receive big triangle
	turn('L', 90);
	move('F', 1);

	putUpLift();
	turn('R', 90);
	move('F', 1);

	move('B', 1);
	putDownLift();

	//

}

putUpLift() {
 setMotorSpeed(leftUp, 100);
 setMotorSpeed(rightUp, 100);
 //Halt program flow for 1000ms (1 second)
 sleep(1000);
 setMotorSpeed(leftUp, 0);
 setMotorSpeed(rightUp, 0);
}
putDownLift() {
 setMotorSpeed(leftUp, -100);
 setMotorSpeed(rightUp, -100);
 //Halt program flow for 1000ms (1 second)
 sleep(1000);
 setMotorSpeed(leftUp, 0);
 setMotorSpeed(rightUp, 0);

}
void turn(string orientation, int degrees) {
	if(orientation == "R") {
		setMotorSpeed(backRight, -100);
 		setMotorSpeed(frontRight, -100);
		setMotorSpeed(frontLeft, 100);
 		setMotorSpeed(frontRight, 100);
 		sleep(1000);
 		setMotorSpeed(backRight, 00);
 		setMotorSpeed(frontRight, 00);
		setMotorSpeed(frontLeft, 00);
 		setMotorSpeed(frontRight, 00);
	}
	if(orientation == "L") {
		setMotorSpeed(backRight, 100);
 		setMotorSpeed(frontRight, 100);
		setMotorSpeed(frontLeft, -100);
 		setMotorSpeed(frontRight, -100);
 		sleep(1000);
 		setMotorSpeed(backRight, 00);
 		setMotorSpeed(frontRight, 00);
		setMotorSpeed(frontLeft, 00);
 		setMotorSpeed(frontRight, 00);
	}
}
